AspHomework2/AspHomework2/Models/ErrorViewModel.cs
using System;

namespace AspHomework2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspHomework2/AspHomework2/Models/HomeViewModel.cs
using System.Collections.Generic;
using AspHomework2.Persistence.Entities;

namespace AspHomework2.Models
{
    public class HomeViewModel
    {
        public int ItemsCount { get; set; }
        
        public List<JobApplication> JobApplications { get; set; } 
    }
}

AspHomework2/AspHomework2/Models/JobApplicationAnswerViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using AspHomework2.Persistence.Entities;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace AspHomework2.Models
{
    public class JobApplicationAnswerViewModel
    {
        [StringLength(1000, ErrorMessage = "Délka odpovědi nesmí přesáhnout 1000 znaků.")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Pole odpověď je povinné.")]
        [DisplayName("Odpověď")]
        public string Answer { get; set; }
        
        [DisplayName("Přijata")]
        public bool Accepted { get; set; }
        
        [BindNever]
        public JobApplication JobApplication { get; set; }
    }
}

AspHomework2/AspHomework2/Models/JobApplicationIndexViewModel.cs
using System.Collections.Generic;
using AspHomework2.Persistence.Entities;

namespace AspHomework2.Models
{
    public class JobApplicationIndexViewModel
    {
        public int ItemsCount { get; set; }
        
        public List<JobApplication> JobApplications { get; set; } 
    }
}

AspHomework2/AspHomework2/Controllers/API/BranchesController.cs
using System.Linq;
using System.Threading.Tasks;
using AspHomework2.Controllers.API.DTOs;
using AspHomework2.Extensions;
using AspHomework2.Hubs;
using AspHomework2.Persistence.Repositories;
using AutoMapper;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace AspHomework2.Controllers.API
{
    [Route("api/branches")]
    public class BranchesController : Controller
    {
        private readonly IBranchRepository _branchRepository;
        private readonly IMapper _mapper;
        private readonly IHubContext<JobApplicationHub> _jobApplicationHubContext;

        public BranchesController(IBranchRepository branchRepository, IMapper mapper)
        {
            _branchRepository = branchRepository;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var branches = _branchRepository.FindAll();

            var mapped = branches.Select(x => _mapper.Map<BranchDto>(x)).ToList();
            
            return Ok(mapped);
        }
    }
}

AspHomework2/AspHomework2/Controllers/API/JobApplicationController.cs
using System.Threading.Tasks;
using AspHomework2.Controllers.API.DTOs;
using AspHomework2.Extensions;
using AspHomework2.Hubs;
using AspHomework2.Persistence.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace AspHomework2.Controllers.API
{
    [Route("api/jobApplication")]
    public class JobApplicationController : Controller
    {
        private readonly IBranchRepository _branchRepository;
        private readonly IHubContext<JobApplicationHub> _jobApplicationHubContext;

        public JobApplicationController(IBranchRepository branchRepository, IHubContext<JobApplicationHub> jobApplicationHubContext)
        {
            _branchRepository = branchRepository;
            _jobApplicationHubContext = jobApplicationHubContext;
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] JobApplicationDto jobApplicationDto)
        {
            if (ModelState.IsValid == false)
            {
                return BadRequest(new ModelStateErrorList(ModelState).AsList());
            }
            
            _branchRepository.Save(jobApplicationDto);

            await _jobApplicationHubContext.Clients.All.SendCoreAsync("Refresh", new object[0]);
            
            return Ok(new
            {
                Success = true
            });
        }

    }
}

AspHomework2/AspHomework2/Controllers/HomeController.cs
using AspHomework2.Models;
using AspHomework2.Persistence.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AspHomework2.Controllers
{
    public class HomeController : Controller
    {
        private readonly IJobApplicationRepository _jobApplicationRepository;

        public HomeController(IJobApplicationRepository jobApplicationRepository)
        {
            _jobApplicationRepository = jobApplicationRepository;
        }
        
        public IActionResult Index()
        {
            return View(CreateViewModel());
        }

        public IActionResult RedrawList()
        {
            return View("_JobApplications", CreateViewModel());
        }

        private HomeViewModel CreateViewModel()
        {
            var viewModel = new HomeViewModel();

            viewModel.JobApplications = _jobApplicationRepository.FindAllForDashboard();
            viewModel.ItemsCount = _jobApplicationRepository.CountAllForDashboard();

            return viewModel;
        }
    }
}

AspHomework2/AspHomework2/Controllers/JobApplicationController.cs
using System.Threading.Tasks;
using AspHomework2.Hubs;
using AspHomework2.Models;
using AspHomework2.Persistence.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace AspHomework2.Controllers
{
    public class JobApplicationController : Controller
    {
        private readonly IJobApplicationRepository _jobApplicationRepository;
        private readonly IHubContext<JobApplicationHub> _jobApplicationHubContext;

        public JobApplicationController(IJobApplicationRepository jobApplicationRepository, IHubContext<JobApplicationHub> jobApplicationHubContext)
        {
            _jobApplicationRepository = jobApplicationRepository;
            _jobApplicationHubContext = jobApplicationHubContext;
        }

        [HttpGet]
        public IActionResult Answer(int id)
        {
            var entity = _jobApplicationRepository.FistOrNullById(id);

            if (entity == null)
            {
                return NotFound();
            }
            
            return View(new JobApplicationAnswerViewModel
            {
                JobApplication = entity
            });
        }

        [HttpPost]
        public async Task<IActionResult> Answer(int id, JobApplicationAnswerViewModel viewModel)
        {
            var entity = _jobApplicationRepository.FistOrNullById(id);

            if (entity == null)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid == false)
            {
                return View(viewModel);
            }
            
            _jobApplicationRepository.ConfirmJobApplication(entity, viewModel);
            await _jobApplicationHubContext.Clients.All.SendCoreAsync("Refresh", new object[0]);

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            var modelView = new JobApplicationIndexViewModel
            {
                ItemsCount = _jobApplicationRepository.CountAllUndone(),
                JobApplications = _jobApplicationRepository.FindAllUndone()
            };

            return View(modelView);
        }
    }
}

AspHomework2/AspHomework2/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Přihlášky";
}

<div>
    <a class="btn btn-primary" asp-action="Index" asp-controller="JobApplication">Další stránka</a>
</div>

<div id="jobApplicationList">
    <partial name="_JobApplications" model="Model"/>
</div>

@section Scripts{
    <script>
        (function() {
            "use strict";
            
            const connection = new signalR.HubConnectionBuilder().withUrl("/applicationHub").build();

            connection.on("Refresh", function () {
                fetch('@Url.Action("RedrawList")').then(async function(response) {
                    const body = await response.text();
                                      
                    document.getElementById("jobApplicationList").innerHTML = body;
                });
            });
              
            connection.start().then(function () {
            }).catch(function (err) {
                return console.error(err.toString());
            });
        })();
    </script>
}

AspHomework2/AspHomework2/Views/Home/_JobApplications.cshtml
@model HomeViewModel

@{
    Layout = null;
}

<h1>Přihlášky (zbývá @Model.ItemsCount)</h1>
<div class="row">
    @foreach (var application in Model.JobApplications)
    {
        <div class="col-md-12">
            <div>#@application.Id</div>
            <div>@application.Created.ToString()</div>
            <a href="javascript:void(0)" onclick="alert('@application.Content')">Zobrazit text přihlášky</a>
            <div>
            <a href="/files/@application.CvFilePath">Soubor</a>    
            </div>
        </div>   
    }
</div>

AspHomework2/AspHomework2/Views/JobApplication/Answer.cshtml
@model JobApplicationAnswerViewModel

@{
    ViewData["Title"] = "Přihláška";
}

<a asp-controller="JobApplication" asp-action="Index">Zpět</a>

<div class="row">
    <div class="col-md-12">
        <div>Číslo: @Model.JobApplication.Id</div>
        <div>Vytvořeno: @Model.JobApplication.Created.ToString()</div>
        <div>Email: @Model.JobApplication.Email</div>
        <div>Telefon: @Model.JobApplication.Phone</div>
        <div>Text přihlášky:</div>
        <p>@Model.JobApplication.Content</p>
        <div>
        <a href="/files/@Model.JobApplication.CvFilePath">Zobrazit soubor</a>    
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    <div>
        <div class="form-group">
            <div>@Html.LabelFor(a => a.Answer)</div>
            <div>@Html.EditorFor(a => a.Answer)</div>
        </div>
        
        <div class="form-group">
            <div>@Html.LabelFor(a => a.Accepted)</div>
            <div>@Html.CheckBoxFor(a => a.Accepted)</div>
        </div>
        
        <div class="form-group">
            @Html.ValidationSummary()
        </div>
        
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Odeslat">
        </div>
    </div>
}

AspHomework2/AspHomework2/Views/JobApplication/Index.cshtml
@model JobApplicationIndexViewModel

@{
    ViewData["Title"] = "Přihlášky";
}

<h1>Všechny přihlášky</h1>

<a asp-controller="Home" asp-action="Index">Zpět</a>

<p>Zbývá @Model.ItemsCount</p>

@foreach (var application in Model.JobApplications)
{
    <div>
        <div>Přihláška č. @application.Id</div>
        <a class="btn btn-primary" asp-action="Answer" asp-route-id="@application.Id">Odpovědět</a>
    </div>
}

AspHomework2/AspHomework2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspHomework2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/signalr/signalr.min.js"></script>
    <partial name="_ValidationScriptsPartial"/>
    <script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>